---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-lab-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.5-192.168.0.10
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-lab-pool-advertise
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-lab-pool
